# Generated by Django 4.2.3 on 2023-08-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_categ_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='print',
            new_name='price',
        ),
    ]
